# Generated by Django 3.1 on 2020-08-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('subtitle', models.CharField(blank=True, max_length=40)),
                ('body', models.TextField()),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
    ]
