# Generated by Django 3.1 on 2020-08-10 05:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20200810_0513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='time',
        ),
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
